services:
  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./caddy-conf:/etc/caddy:ro
  backend:
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: ./backend/
      dockerfile: backend/Dockerfile
    volumes:
      - ./data:/data:rw