services:
  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "8866:80"
    volumes:
      - ./caddy-conf:/etc/caddy:ro
  backend:
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - ./data/:/data/:rw
  
  frontend:
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: ./frontend/
      dockerfile: Dockerfile